name: Azure ML Trigger Pipeline Sample

on:
  repository_dispatch:
    types: [hoge] 

defaults:
  run:
    working-directory: openhack

permissions:
      id-token: write
      contents: read

jobs:
  job-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{secrets.AZURE_CREDENTIALS}}'
      - name: Install ML extension for az command
        run: az extension add --name ml --version 2.4.1
      - name: check Directory
        run: |
          ls -la
      - name: Create ML Job
        run: az ml online-deployment create -f 03_managed_deployment.yml -g ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} -w ${{ secrets.AZURE_ML_WORKSPACE_NAME }}
